name: CI build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.3.0
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release ./src/ClashOfClans.sln
    - name: CI build
      working-directory: ./build
      shell: pwsh
      run: ./build.ps1 -ci
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'
    - name: Publish the package to GPR
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      working-directory: ./src
      run: |
        nuget sources add -name "GPR" -source "https://nuget.pkg.github.com/tparviainen/index.json" -username tparviainen -password ${{secrets.GITHUB_TOKEN}}
        nuget push ClashOfClans/bin/Release/*.nupkg -source "GPR"
