name: CI build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release ./src/ClashOfClans.sln
    - name: CI build
      working-directory: ./build
      shell: pwsh
      run: ./build.ps1 -ci
    - name: Publish the package to GPR
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      working-directory: ./src
      run: dotnet nuget push ClashOfClans/bin/Release/*.nupkg --source "github"
